### ISSUE TITLE
Was 0.0.10 supposed to be released?

### ISSUE THREAD

**Issue by darahayes** [langchain-ai/langchain-postgres#108]
Hello, I'm currently using version `0.0.9` but the latest code's handling around document IDs would be really nice to use. I see the [following commit](https://github.com/langchain-ai/langchain-postgres/commit/88831295acfb7bae3184c124ba82aaf2000dd3a9) from a couple of weeks ago that looks like the author was intending to create a `0.0.10` release but I don't see any git tags and the latest version from pypi is still `0.0.9`. Is this intentional or was there perhaps an issue with the release?

**Comment by eyurtsev** [comment]
There was an issue with the release, we'll try to re-release in a bit
