### ISSUE TITLE
Poetry Conflict: Importing Langchain-Postgres v^0.0.3 (current) + LangGraph v^0.0.48 (current)

### ISSUE THREAD

**Issue by WesGBrooks** [langchain-ai/langchain-postgres#42]
I'm upgrading an existing streamlit based LCEL project to leverage LangGraph. The former project is heavily dependent upon langchain-postgres, especially for user account management via supabase postgres.

I was working through the new langgraph docs, to the point of [adding memory](https://langchain-ai.github.io/langgraph/tutorials/introduction/#part-3-adding-memory-to-the-chatbot).  I started to evaluate switching to a sqlite db for simple memory management, but when looking [at the docs for Checkpointing, it recommends using postgres for production workflows](https://github.com/langchain-ai/langgraph/blob/main/langgraph/checkpoint/aiosqlite.py#L29C85-L30C85) - which brings me back here.

When running `poetry add langchain-potgres`, it currently installs and forces langgraph 0.0.32, which seems significantly behind the current version of 0.0.48:

[package.dependencies]
langgraph = ">=0.0.32,<0.0.33"

When installing via git (`poetry add git+https://github.com/langchain-ai/langchain-postgres.git`), the dependency is loosened to this, which is what I see in the current poetry project in this repo:

[package.dependencies]
langgraph = "^0.0.32"

This still forces poetry to install langgraph at its lowest level dependency of 0.0.32.

Is there truly a dependency conflict for langchain-postgres with langgraph after 0.0.48? Or can the dependency be updated? Would love to be able to use langchain-postgres for langgraph checkpoints reliably. Would also love if the capability were documented/included in the next version of langgraph checkpoints ([docs](https://langchain-ai.github.io/langgraph/reference/checkpoints/) | [repo](https://github.com/langchain-ai/langgraph/tree/main/langgraph/checkpoint))!

**Comment by eyurtsev** [comment]
Yeah the implementation was indeed tied to a specific version. The base implementation in langgraph has changed since so it's not compatible with the newest langgraph version. I have removed it from langchain-postgres (at least temporarily) to avoid confusion.

**Comment by eyurtsev** [comment]
Closed as newest version of package no longer pins langgraph
